include(ExternalProject)

set(DISABLE_MODULES
  CRYPTO DATA ENCODINGS JSON
  MONGODB NET NETSSL PAGECOMPILER
  PAGECOMPILER_FILE2PAGE REDIS XML ZIP)

set(POCO_CMAKE_ARG)
foreach(mod ${DISABLE_MODULES})
  set(POCO_CMAKE_ARG "${POCO_CMAKE_ARG} -DENABLE_${mod}=OFF")
endforeach()
  
ExternalProject_Add(
  POCO
  GIT_REPOSITORY https://github.com/pocoproject/poco
  GIT_TAG poco-1.9.0-release
  CMAKE_ARGS ${POCO_CMAKE_ARG} -DCMAKE_INSTALL_PREFIX=${PROJECT_DEPS_DIR}/poco
  -DCMAKE_INSTALL_MESSAGE=LAZY
  )
